use DataWarehouseAnalytics--- explore all objects in the data base 
select * from INFORMATION_SCHEMA.TABLES 


--- explore all objects in the data base 
select * from INFORMATION_SCHEMA.columns 

---dimension exploration 
--- distinct to show all uniqe values 
select distinct country from gold.dim_customers  
select * from gold.dim_customers
   --- explore all category "the major division "
select distinct category,subcategory,product_name 
from gold.dim_products   
--- date exploration 

---identifye the earlist and the latest dates (boundaries) undrestand the scope of data and timespan
-- earlist date 
select min(order_date) as first_date,max (order_date) as last_date
, datediff(year, min(order_date),max (order_date)) as boundary 
from gold.fact_sales  
--- find the youngest and the oldest customer 
select min (birthdate) as oldest_birthdate,
datediff(YEAR,MIN(birthdate),getdate()) as oldest_age ,
max(birthdate) as youngest_customer ,
datediff(year,max(birthdate),GETDATE()) youngest_age 
from gold.dim_customers
---find yhe total sales 
select sum(sales_amount) as total_sales from gold.fact_sales
---find how many items are sold 
select sum(quantity) as total_quantity  from gold.fact_sales
---find the total number of products 
--- find the avrage selling price 
select avg(price) as avg_price  from gold.fact_sales
---find the total number of order 
select count (order_number) as total_order from gold.fact_sales
select count ( distinct order_number) as total_order from gold.fact_sales
---find the total number of product 
select count ( distinct product_name) as total_products  from gold.dim_products
---find the total number of customer  that has placed an order 
select count ( distinct customer_key) as total_order from gold.dim_customers
--- generte a report that shows all key metrics of the business 
select 'total_sales' as measure_name,SUM(sales_amount) as measure_value from gold.fact_sales
union all 
select 'total_quantity',SUM(quantity ) as measure_value from gold.fact_sales 
union all 
select 'average_price ',avg(price ) as measure_value from gold.fact_sales 
union all 
select 'total_number_of order',count(distinct order_number ) as measure_value from gold.fact_sales
union all 
select 'total_num of product' ,count (distinct product_name ) as measure_value from gold.dim_products 
union all 
select 'total_num_ of customer ' ,count ( distinct customer_key ) as measure_value from gold.fact_sales  
 
---comparing the ,easure alues by category (magnitude analysis )
--- find total customer by countries 
select  country ,count(distinct customer_key) as total_custmoer from gold.dim_customers 
group by country
order by total_custmoer desc 
--- find total customer by gender 
select  gender ,count(distinct customer_key) as total_custmoer from gold.dim_customers 
group by gender
order by total_custmoer desc 
--- find the total products  by category 
select  category  ,count(distinct product_key) as total_products  from gold.dim_products 
group by category
order by total_products  desc 
--- what is the avergae costs in each category ?
select  category  ,avg( cost) as avg_costs  from gold.dim_products 
group by category
order by avg_costs  desc 
--- what is the total revenue generated for each category ? i usally start with the fact then left join the dimension to it 
select p.category 
,sum(f.sales_amount) total_revenue 
from gold.fact_sales  f
left join  gold.dim_products p 
on p.product_key =f.product_key
group by p.category
order by total_revenue desc 
--- find total revenue is generated by each customer 
select c.customer_key ,
c.first_name,
c.last_name
,sum(f.sales_amount) total_revenue 
from gold.fact_sales  f
left join  gold.dim_customers c
on c.customer_key =f.customer_key 
group by   c.customer_key ,
c.first_name,
c.last_name
order by total_revenue desc 
--- what is the distribution of sold item across countries ?

select c.country
,sum(f.quantity) total_quantity  
from gold.fact_sales  f
left join  gold.dim_customers c
on c.customer_key =f.customer_key 
group by   c.country
order by total_quantity desc 

--- which 5 product generate the hoghest revenue 
--- ranking analysis 
select top 5 
p.product_name 
,sum(f.sales_amount) total_revenue 
from gold.fact_sales  f
left join  gold.dim_products p 
on p.product_key =f.product_key
group by p.product_name
order by total_revenue desc 
---which 5 worst product in item of sales ? 
select top 5 
p.product_name 
,sum(f.sales_amount) total_revenue 
from gold.fact_sales  f
left join  gold.dim_products p 
on p.product_key =f.product_key
group by p.product_name
order by total_revenue  

---which 5 worst product in item of sales  with row number column ?
select * from (
select 
p.product_name 
,sum(f.sales_amount) total_revenue ,
ROW_NUMBER() over (order by sum(f.sales_amount) desc ) as rank_product 
from gold.fact_sales  f
left join  gold.dim_products p 
on p.product_key =f.product_key
group by p.product_name) t 
where rank_product <=5    --- this equal to the next 
------------------------------------------------------- 
select  top 5 
p.product_name 
,sum(f.sales_amount) total_revenue ,
ROW_NUMBER() over (order by sum(f.sales_amount) desc ) as rank_product 
from gold.fact_sales  f
left join  gold.dim_products p 
on p.product_key =f.product_key
group by p.product_name 
